use_frameworks!

target 'GitHubActionPodDemo_Example' do
  pod 'GitHubActionPodDemo', :path => '../'

  target 'GitHubActionPodDemo_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
