use_frameworks!

target 'GitHubActionPodDemo_Example' do
  pod 'GitHubActionPodDemo', :path => '../'

  target 'GitHubActionPodDemo_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
